# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ bonus ]

  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@bonus
    - name: Install Dependencies
      run:  npm ci
    - name: Build dependencies
      run:  npm run build
    - name: Archive production artifact
      uses: actions/upload-artifact@bonus
      with:
        name: dist
        path: dist
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@bonus
      - name: Download artifact
        uses: actions/download-artifact@bonus
        with:
          name: dist
          path: dist
      - name: Deploy to firebase
        uses: w9jds/firebase-action@bonus
        with:
          args: deploy --only hosting
        env:
          FIREBAES_TOKEN: ${{secrets.FIREBASE_TOKEN}}
